#!/bin/bash

# source for bashrc_helper for all dotfiles

export PATH=$PATH:/Users/iqbalaulakh/:/Users/iqbalaulakh/Documents/:/opt/homebrew/bin
#source /Users/iqbalaulakh/bashrc_helpers/helpers.sh

# Setting PATH for Python 3.13
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.13/bin:${PATH}"
export PATH

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/iqbalaulakh/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/iqbalaulakh/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/iqbalaulakh/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/iqbalaulakh/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
